### DISCUSSION TITLE
Relaxing maturin version pin for minijinja-py

### DISCUSSION THREAD

**Discussion by synapticarbors** [mitsuhiko/minijinja#566] [General]
Currently `minijinja-py` has a pyproject.toml defining:

```toml
[build-system]
requires = ["maturin>=0.15,<0.16"]
```

I was wondering if there were any blockers that would make it difficult to relax the `maturin` constraint to allow for newer versions? The last compatible maturin release (0.15.3) was from May 2023, and the latest version is 1.7.1.
