### ISSUE TITLE
Autoreload doesn't work by itself

### ISSUE THREAD

**Issue by Christoph-AK** [mitsuhiko/minijinja#247]
Hey there, thanks for the crate! 
I want to use minijinja in a small webserver project and want to utilise autoreload in dev mode. 

Unfortunately the auto reload, even nearly 1:1 copied from the example, doesn't detect file changes automatically. The env reload only when calling request_reload manually.

I'm on windows 11. 

Is this a mistake on my part, or a bug in the crate?

Cargo.toml:
```toml
[dependencies]
actix = "0.13"
actix-web = "4"
ansi-to-html = "0.1"
color-eyre = "0.6"
env_logger = "0.10"
itertools = "0.10"
log = "0.4"
minijinja = { version = "0.31", features = ["source"] }
minijinja-autoreload = { version = "0.31", features = ["watch-fs"] }
once_cell = "1"
ramhorns = "0.14"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.6", features = [
    "mysql",
    "runtime-tokio-rustls",
    "time",
    "chrono",
] }
``` 

main.rs
```rust

pub static TEMPLATE_WATCHER: OnceCell<AutoReloader> = OnceCell::new();

#[get("/")]
async fn index() -> Result<HttpResponse> {
    let out = get_template("index.html", context!())?;

    Ok(HttpResponse::build(StatusCode::OK).body(out))
}

pub fn get_template(name: &str, ctx: Value) -> Result<String> {
    let reloader = TEMPLATE_WATCHER.get().unwrap();
    reloader.notifier().request_reload(); // <-- without this, the reload never gets triggered,
    let env = reloader
        .acquire_env()
        .http_internal_error("tpl acquire env")?;
    let tpl = env.get_template(name).http_internal_error("get template")?;
    tpl.render(ctx).http_internal_error("render template")
}


#[actix_web::main]
async fn main() -> std::io::Result<()> {
    color_eyre::install().unwrap();
    std::env::set_var("RUST_LOG", "debug,sqlx=warn,actix_server=warn");
    std::env::set_var("RUST_BACKTRACE", "1");
    env_logger::init();
    let reloader = AutoReloader::new(move |notifier| {
        info!("recreate env");
        let mut env = Environment::new();
        let template_path = std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("templates");
        notifier.watch_path(&template_path, true);
        env.set_source(Source::from_path(template_path));
        Ok(env)
    });

    if TEMPLATE_WATCHER.set(reloader).is_err() {
        panic!("couldn't set global template watcher")
    };

    let db_pool = sqlx::MySqlPool::connect("mysql://root@127.0.0.1:3306/ankerlunch")
        .await
        .unwrap();

    HttpServer::new(move || {
        App::new()
            .wrap_fn(|req, srv| {
                let fut = srv.call(req);
                async {
                    let mut res = fut.await?;
                    if !res.status().is_success() {
                        res.headers_mut()
                            .insert(CONTENT_TYPE, HeaderValue::from_static("text/html"));
                    }
                    Ok(res)
                }
            })
            .app_data(Data::new(db_pool.clone()))
            .service(user)
            .service(index)
            .service(login_with_token)
            .service(login_get)
            .service(login_post)
    })
    .bind(("0.0.0.0", 8080))?
    .run()
    .await
}
```
